[package]
name = "bitwarden_rs"
version = "1.0.0"
authors = ["Daniel García <dani-garcia@users.noreply.github.com>"]

[dependencies]
# Web framework for nightly with a focus on ease-of-use, expressibility, and speed.
rocket = { version = "0.3.16", features = ["tls"] }
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"

# HTTP client
reqwest = "0.8.8"

# multipart/form-data support
multipart = "0.15.2"

# A generic serialization/deserialization framework
serde = "1.0.74"
serde_derive = "1.0.74"
serde_json = "1.0.26"

# A safe, extensible ORM and Query builder
diesel = { version = "1.3.2", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }

# Bundled SQLite
libsqlite3-sys = { version = "0.9.3", features = ["bundled"] }

# Crypto library
ring = { version = "= 0.11.0", features = ["rsa_signing"] }

# UUID generation
uuid = { version = "0.6.5", features = ["v4"] }

# Date and time library for Rust
chrono = "0.4.5"

# TOTP library
oath = "0.10.2"

# Data encoding library
data-encoding = "2.1.1"

# JWT library
jsonwebtoken = "= 4.0.1"

# U2F library
u2f = "0.1.2"

# A `dotenv` implementation for Rust
dotenv = { version = "0.13.0", default-features = false }

# Lazy static macro
lazy_static = "1.1.0"

# Numerical libraries
num-traits = "0.2.5"
num-derive = "0.2.2"

[patch.crates-io]
 # Make jwt use ring 0.11, to match rocket
jsonwebtoken = { path = "libs/jsonwebtoken" }

# Version 0.1.2 from crates.io lacks a commit that fixes a certificate error
u2f = { git = 'https://github.com/wisespace-io/u2f-rs', rev = '193de35093a44' }
